/**
 * Parse QUIZ-BANK-DECK1.md → lib/quiz/deck1Bank.ts
 *
 * The markdown is the authoring source of truth. Run after editing it:
 *   npx tsx scripts/gen-quiz-bank.ts
 *
 * Item format in the md:
 *   **d1-l2-slug** · card 5           (or  · cards 27 & 18)
 *   Question text, possibly
 *   wrapped across lines.
 *   - **✓ correct option**
 *   - distractor one
 *   - distractor two
 *   - distractor three
 *   > Explanation, possibly
 *   > across lines.
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "QUIZ-BANK-DECK1.md");
const OUT = join(ROOT, "lib", "quiz", "deck1Bank.ts");

type Level = 1 | 2 | 3;
interface BankItem {
  id: string;
  level: Level;
  cardIds: number[];
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

function clean(s: string): string {
  return s
    .replace(/\*\*/g, "")
    .replace(/\*/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

const lines = readFileSync(SRC, "utf8").split("\n");
const items: BankItem[] = [];
let level: Level | null = null;

let i = 0;
while (i < lines.length) {
  const line = lines[i];

  const lvlMatch = line.match(/^##\s+L([123])\s+—/);
  if (lvlMatch) {
    level = Number(lvlMatch[1]) as Level;
    i++;
    continue;
  }

  const idMatch = line.match(/^\*\*(d1-l[123]-[a-z0-9-]+)\*\*\s+·\s+cards?\s+([\d\s&,]+?)\s*$/);
  if (idMatch && level) {
    const id = idMatch[1];
    const cardIds = idMatch[2]
      .split(/[\s&,]+/)
      .filter(Boolean)
      .map(Number);

    // question: following lines until first "- "
    i++;
    const qLines: string[] = [];
    while (i < lines.length && !lines[i].startsWith("- ")) {
      if (lines[i].trim()) qLines.push(lines[i].trim());
      i++;
    }
    const question = clean(qLines.join(" "));

    // options: consecutive "- " lines
    const options: string[] = [];
    let correctIndex = -1;
    while (i < lines.length && lines[i].startsWith("- ")) {
      const raw = lines[i].slice(2);
      const isCorrect = /✓/.test(raw); // ✓
      const text = clean(raw.replace(/✓/, ""));
      if (isCorrect) correctIndex = options.length;
      options.push(text);
      i++;
    }

    // explanation: "> " lines (may be preceded by a blank line)
    while (i < lines.length && !lines[i].startsWith("> ") && !lines[i].trim()) i++;
    const eLines: string[] = [];
    while (i < lines.length && lines[i].startsWith("> ")) {
      eLines.push(lines[i].slice(2).trim());
      i++;
    }
    const explanation = clean(eLines.join(" "));

    if (options.length !== 4) {
      throw new Error(`${id}: expected 4 options, got ${options.length}`);
    }
    if (correctIndex < 0) {
      throw new Error(`${id}: no correct option marked`);
    }
    if (!question || !explanation) {
      throw new Error(`${id}: missing question or explanation`);
    }
    items.push({ id, level, cardIds, question, options, correctIndex, explanation });
    continue;
  }

  i++;
}

const byLevel = { 1: 0, 2: 0, 3: 0 } as Record<Level, number>;
for (const it of items) byLevel[it.level]++;

const seen = new Set<string>();
for (const it of items) {
  if (seen.has(it.id)) throw new Error(`duplicate id: ${it.id}`);
  seen.add(it.id);
}

const header = `// AUTO-GENERATED by scripts/gen-quiz-bank.ts from QUIZ-BANK-DECK1.md
// Do not edit by hand — edit the markdown and re-run the script.
// L1: ${byLevel[1]}  ·  L2: ${byLevel[2]}  ·  L3: ${byLevel[3]}  ·  total: ${items.length}

import type { QuizItem } from "./bank";

export const DECK1_BANK: QuizItem[] = ${JSON.stringify(
  items.map((it) => ({
    id: it.id,
    deckId: 1,
    level: it.level,
    cardIds: it.cardIds,
    question: it.question,
    options: it.options,
    correctIndex: it.correctIndex,
    explanation: it.explanation,
  })),
  null,
  2
)};
`;

writeFileSync(OUT, header);
console.log(`Wrote ${items.length} items → ${OUT}`);
console.log(`  L1 ${byLevel[1]} · L2 ${byLevel[2]} · L3 ${byLevel[3]}`);
