// AUTO-GENERATED by scripts/gen-quiz-bank.ts from QUIZ-BANK-DECK1.md
// Do not edit by hand — edit the markdown and re-run the script.
// L1: 25  ·  L2: 35  ·  L3: 25  ·  total: 85

import type { QuizItem } from "./bank";

export const DECK1_BANK: QuizItem[] = [
  {
    "id": "d1-l1-homoousios",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      1
    ],
    "question": "Which Greek term names the claim that the Son is of the same being as the Father?",
    "options": [
      "homoousios",
      "hypostasis",
      "perichōrēsis",
      "kenōsis"
    ],
    "correctIndex": 0,
    "explanation": "Homoousios = \"same being,\" fixed at Nicaea (325). One iota separates it from homoiousios, \"similar being\" — the compromise Nicaea rejected. Hypostasis is \"person,\" perichōrēsis the Persons' mutual indwelling, kenōsis Christ's self-emptying."
  },
  {
    "id": "d1-l1-perichoresis",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      5
    ],
    "question": "Perichōrēsis, the term for the inner life of the Trinity, means:",
    "options": [
      "mutual indwelling",
      "eternal begetting",
      "undivided essence",
      "equal in glory"
    ],
    "correctIndex": 0,
    "explanation": "The three Persons live completely in one another (John 17:21) — not three parts standing side by side. The other three phrases are true of God but name different things."
  },
  {
    "id": "d1-l1-bara",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      6
    ],
    "question": "In Genesis 1:1 the Hebrew verb bara (\"created\") is unlike ordinary words for making because:",
    "options": [
      "in the Old Testament it is used only with God as its subject",
      "it always refers to shaping something from material already there",
      "it is interchangeable with the ordinary Hebrew word for \"make\"",
      "it means \"to arrange\" rather than \"to originate\""
    ],
    "correctIndex": 0,
    "explanation": "Bara is never used of human making and never requires raw material — it carries the sense of bringing into being what was not there. Yatsar, \"to form,\" is the word for shaping existing stuff."
  },
  {
    "id": "d1-l1-pantokrator",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      8
    ],
    "question": "Pantokratōr, the title behind \"God's sovereignty,\" is best translated:",
    "options": [
      "ruler of all / holder of all power",
      "maker of all",
      "knower of all",
      "judge of all"
    ],
    "correctIndex": 0,
    "explanation": "Pan (\"all\") + kratōr (\"ruler\"). It names God's actual rule over everything, not merely His ability to rule. The other three are true of God but are different words — Creator, omniscient, Judge."
  },
  {
    "id": "d1-l1-hypostatic-union",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      11
    ],
    "question": "The term hypostatic union (henōsis hypostatikē) refers to:",
    "options": [
      "two natures, divine and human, united in Christ's one person",
      "the union of the three persons in one divine essence",
      "the believer's union with Christ by faith",
      "the joining of Christ's will to the Father's will"
    ],
    "correctIndex": 0,
    "explanation": "Hypostasis = \"person.\" The hypostatic union joins full deity and full humanity in the single person of the Son — not a Trinity term, and not the same as the believer's union with Christ."
  },
  {
    "id": "d1-l1-kippur",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      13
    ],
    "question": "The Hebrew word kippur, behind \"atonement,\" carries the root idea of:",
    "options": [
      "covering",
      "cutting / making a covenant",
      "ransoming a slave",
      "washing clean"
    ],
    "correctIndex": 0,
    "explanation": "Kippur — to cover. On the Day of Atonement the blood \"covered\" the people's sin before God. \"Ransom\" and \"cleansing\" are other biblical pictures of the same rescue, but different words."
  },
  {
    "id": "d1-l1-anastasis",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      14
    ],
    "question": "Anastasis, the New Testament word for resurrection, literally means:",
    "options": [
      "a standing up again",
      "a waking from sleep",
      "a passing over",
      "a carrying up"
    ],
    "correctIndex": 0,
    "explanation": "Ana (\"again/up\") + stasis (\"standing\") — the body raised and standing, not a metaphor for the soul surviving death. \"Carrying up\" (analēpsis) is the word for the ascension."
  },
  {
    "id": "d1-l1-parakletos",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      16
    ],
    "question": "Paraklētos, Jesus' name for the Spirit in John 14, means:",
    "options": [
      "one called alongside to help",
      "one sent ahead to prepare the way",
      "one who speaks for God to the people",
      "one who covers over faults"
    ],
    "correctIndex": 0,
    "explanation": "Para (\"alongside\") + klētos (\"called\") — an advocate or helper summoned to your side. \"One who speaks for God to the people\" is a prophet (prophētēs)."
  },
  {
    "id": "d1-l1-palingenesia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      17
    ],
    "question": "Palingenesia, translated \"regeneration,\" means:",
    "options": [
      "new birth / becoming again",
      "turning around",
      "growing up to maturity",
      "being set apart"
    ],
    "correctIndex": 0,
    "explanation": "Palin (\"again\") + genesis (\"birth\") — the once-for-all new birth by the Spirit (Titus 3:5). \"Turning around\" is repentance (metanoia); \"being set apart\" is sanctification (hagiasmos)."
  },
  {
    "id": "d1-l1-charismata",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      20
    ],
    "question": "The word charismata (\"spiritual gifts\") is formed directly from the Greek word for:",
    "options": [
      "grace (charis)",
      "power (dunamis)",
      "service (diakonia)",
      "calling (klēsis)"
    ],
    "correctIndex": 0,
    "explanation": "A charisma is a \"grace-gift\" — a concrete expression of God's grace given for the good of others (1 Cor 12:7), not a reward for merit or a badge of status."
  },
  {
    "id": "d1-l1-hamartia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      22
    ],
    "question": "Hamartia, the New Testament word for sin, literally means:",
    "options": [
      "missing the mark",
      "breaking a written law",
      "owing a debt you can't repay",
      "rebelling against a king"
    ],
    "correctIndex": 0,
    "explanation": "All four are biblical pictures of sin, but hamartia is the archer's word — falling short of the target (Romans 3:23). Sin is first a failure to hit what we were made for, not only rule-breaking."
  },
  {
    "id": "d1-l1-charis",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      24
    ],
    "question": "In Paul's usage, charis (\"grace\") most precisely means:",
    "options": [
      "undeserved favor, freely given",
      "a reward earned by faith",
      "a second chance after failure",
      "pity shown to the weak"
    ],
    "correctIndex": 0,
    "explanation": "Charis is a gift with no strings and no prior claim on it (Eph 2:8–9). Making it a reward-for-faith or a second chance smuggles merit back in."
  },
  {
    "id": "d1-l1-metanoia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      26
    ],
    "question": "Metanoia, the word translated \"repentance,\" means:",
    "options": [
      "a change of mind that changes direction",
      "deep sorrow over sin",
      "confession of specific sins",
      "making amends for wrongs done"
    ],
    "correctIndex": 0,
    "explanation": "Meta (\"change\") + nous (\"mind\"). Sorrow, confession, and restitution may flow from it, but repentance itself is the turn — a new mind that walks a new way."
  },
  {
    "id": "d1-l1-en-christo",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      28
    ],
    "question": "The phrase en Christō (\"in Christ\"), which recurs over 160 times in Paul, points to:",
    "options": [
      "the believer's real inclusion in Christ, so His death and life count as ours",
      "imitating Christ's example closely",
      "living inside a Christian community",
      "holding correct beliefs about Christ"
    ],
    "correctIndex": 0,
    "explanation": "To be \"in Christ\" is to be joined to Him so completely that what is true of Him becomes true of you (Gal 2:20) — crucified, raised, and seated with Him."
  },
  {
    "id": "d1-l1-huiothesia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      29
    ],
    "question": "Huiothesia, the word for adoption, literally means:",
    "options": [
      "placing as a son",
      "raising an orphan",
      "naming an heir",
      "taking in a guest"
    ],
    "correctIndex": 0,
    "explanation": "Huios (\"son\") + thesis (\"placing\"). In the Roman world it was an irrevocable legal act granting the full rights of a natural-born heir — Paul's picture of our standing in God's family (Rom 8:15)."
  },
  {
    "id": "d1-l1-basileia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      32
    ],
    "question": "Basileia tou Theou (\"kingdom of God\") refers first of all to:",
    "options": [
      "God's reign and rule breaking in",
      "a place believers go after death",
      "the visible church on earth",
      "the nation of Israel restored"
    ],
    "correctIndex": 0,
    "explanation": "Basileia is \"kingship\" before it is \"kingdom\" — the active rule of God, arriving in Jesus' ministry (Matt 4:17) and not yet complete. A realm follows from a reign."
  },
  {
    "id": "d1-l1-theopneustos",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      33
    ],
    "question": "Theopneustos, Paul's word for Scripture in 2 Timothy 3:16, means:",
    "options": [
      "God-breathed",
      "God-spoken",
      "God-given",
      "God-approved"
    ],
    "correctIndex": 0,
    "explanation": "Theos + pneō, \"to breathe.\" Scripture is breathed out by God — divine in origin, even as real human authors wrote it."
  },
  {
    "id": "d1-l1-logos",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      35
    ],
    "question": "When John calls Jesus the Logos (\"the Word\") in John 1, he means:",
    "options": [
      "God's own self-expression, personally present",
      "a written record of God's laws",
      "a wise saying or piece of teaching",
      "a prophetic message spoken aloud"
    ],
    "correctIndex": 0,
    "explanation": "Logos is speech that reveals the speaker. John says the Word who was with God and was God became flesh — God making Himself known in person. A spoken prophetic message is rhēma."
  },
  {
    "id": "d1-l1-ekklesia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      36
    ],
    "question": "Ekklēsia, the New Testament word for \"church,\" means:",
    "options": [
      "an assembly of those called out and gathered",
      "a sacred building set apart for worship",
      "a ranked order of ordained leaders",
      "a region under a bishop's care"
    ],
    "correctIndex": 0,
    "explanation": "Ek (\"out\") + kaleō (\"call\") — people summoned together by God, not a building or an institution. The English \"church\" descends from a different word (kyriakon, \"belonging to the Lord\")."
  },
  {
    "id": "d1-l1-baptisma",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      38
    ],
    "question": "Baptisma / baptizō, the word behind \"baptism,\" basically means:",
    "options": [
      "to dip or immerse",
      "to sprinkle lightly",
      "to wash the hands",
      "to anoint with oil"
    ],
    "correctIndex": 0,
    "explanation": "The same word was used for dyeing cloth and for a ship going under. Paul reads the going-down and coming-up as dying and rising with Christ (Rom 6:3–4)."
  },
  {
    "id": "d1-l1-koinonia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      39
    ],
    "question": "Koinōnia, Paul's word for the Lord's Supper in 1 Corinthians 10:16, carries the sense of:",
    "options": [
      "a sharing / participation in",
      "a remembrance of",
      "a thanksgiving for",
      "a covenant renewal with"
    ],
    "correctIndex": 0,
    "explanation": "\"The cup of blessing... is it not a koinōnia in the blood of Christ?\" The table is real participation in Christ, more than a memorial. Anamnēsis is \"remembrance,\" eucharistia \"thanksgiving\" — adjacent words, different weight."
  },
  {
    "id": "d1-l1-agape",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      41
    ],
    "question": "In the New Testament, agapē is set apart from the other Greek words for love because it names:",
    "options": [
      "a deliberate, self-giving love that seeks another's good",
      "love between close friends",
      "romantic or desiring love",
      "natural affection within a family"
    ],
    "correctIndex": 0,
    "explanation": "Philia is friendship, erōs desire, storgē family affection. Agapē is love as a chosen commitment — the love God is, and the love He commands (John 13:34–35)."
  },
  {
    "id": "d1-l1-hypomone",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      43
    ],
    "question": "Hypomonē, translated \"perseverance\" or \"endurance,\" literally means:",
    "options": [
      "remaining under",
      "pressing forward",
      "standing firm against",
      "waiting quietly for"
    ],
    "correctIndex": 0,
    "explanation": "Hypo (\"under\") + menō (\"remain\"). Not gritting through or escaping the weight, but staying under it until it finishes its work (Heb 10:36; Jas 1:3)."
  },
  {
    "id": "d1-l1-parousia",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      46
    ],
    "question": "Parousia, the main New Testament word for Christ's return, means:",
    "options": [
      "arrival and personal presence",
      "the unveiling of what was hidden",
      "the day of the Lord's wrath",
      "a sudden snatching away"
    ],
    "correctIndex": 0,
    "explanation": "Parousia was used for the state visit of a king. Two other words name facets of the same event: apokalypsis (\"unveiling\") and epiphaneia (\"appearing\")."
  },
  {
    "id": "d1-l1-zoe-aionios",
    "deckId": 1,
    "level": 1,
    "cardIds": [
      50
    ],
    "question": "Zōē aiōnios (\"eternal life\"), as Jesus defines it in John 17:3, is primarily:",
    "options": [
      "a kind of life — knowing God — that begins now",
      "unending existence after death",
      "a reward handed out at the final judgment",
      "the soul's natural immortality"
    ],
    "correctIndex": 0,
    "explanation": "Aiōnios means \"of the age to come\" as much as \"endless.\" Jesus locates eternal life in knowing the Father and the Son — a quality of life already begun, not only a length of time still ahead."
  },
  {
    "id": "d1-l2-homoousios-arianism",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      1
    ],
    "question": "The word homoousios was written into the Nicene Creed (325) to rule out:",
    "options": [
      "Arianism",
      "Pelagianism",
      "Nestorianism",
      "Gnosticism"
    ],
    "correctIndex": 0,
    "explanation": "Arius taught the Son was the first and highest creature. Homoousios — same being as the Father — says the Son is fully God and uncreated. (Pelagianism is about sin and grace; Nestorianism about Christ's natures; Gnosticism about matter and secret knowledge.)"
  },
  {
    "id": "d1-l2-begotten-not-made",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      3
    ],
    "question": "In the Nicene Creed, the phrase \"begotten, not made\" means that the Son:",
    "options": [
      "is eternally from the Father's own being, never brought into existence",
      "was the first thing the Father made, before anything else",
      "proceeds from the Father in the same way the Spirit does",
      "became the Son at the moment of the incarnation"
    ],
    "correctIndex": 0,
    "explanation": "\"Begotten\" keeps the Son's origin in God and outside of time; \"not made\" denies He is a creature. The creed's point against Arius: there was never a time when the Son was not."
  },
  {
    "id": "d1-l2-spirit-constantinople",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      4
    ],
    "question": "The Council of Constantinople (381) expanded the creed to confess that the Holy Spirit:",
    "options": [
      "is worshiped and glorified together with the Father and the Son",
      "proceeds from the Son alone",
      "is a created power rather than a person",
      "became divine at Pentecost"
    ],
    "correctIndex": 0,
    "explanation": "Constantinople settled the Spirit's full deity against those who honored the Father and Son but treated the Spirit as a force. (The \"from the Son\" question — the filioque — is a later Western addition and a separate dispute.)"
  },
  {
    "id": "d1-l2-creator-gnosticism",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      6
    ],
    "question": "The church confessed the one true God as \"maker of heaven and earth, of all things visible and invisible\" chiefly against:",
    "options": [
      "Gnosticism, which said matter is evil and made by a lesser god",
      "Arianism, which said the Son is a creature",
      "Docetism, which said Christ only seemed to have a body",
      "Montanism, which claimed fresh prophecy above Scripture"
    ],
    "correctIndex": 0,
    "explanation": "Gnostic systems split a good spirit-world from an evil material one made by a lower deity. Genesis 1 and the creed insist the one God made everything, and made it good."
  },
  {
    "id": "d1-l2-perichoresis-damascus",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      5
    ],
    "question": "The term perichōrēsis — the divine Persons containing one another without blurring — was given its classic form by:",
    "options": [
      "John of Damascus (8th century)",
      "Augustine of Hippo",
      "Thomas Aquinas",
      "Athanasius of Alexandria"
    ],
    "correctIndex": 0,
    "explanation": "John of Damascus used it to guard the Trinity from two errors at once: dividing God into three, or collapsing Him into one."
  },
  {
    "id": "d1-l2-resurrection-futile",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      14
    ],
    "question": "Paul writes that if one thing is not true, \"your faith is worthless; you are still in your sins\" (1 Corinthians 15:17). He means:",
    "options": [
      "the resurrection",
      "the incarnation",
      "the atoning death",
      "the second coming"
    ],
    "correctIndex": 0,
    "explanation": "1 Corinthians 15 stakes the whole gospel on the risen Christ. Take the resurrection away and, Paul says, forgiveness itself falls with it."
  },
  {
    "id": "d1-l2-chalcedon-eutyches",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      11
    ],
    "question": "Chalcedon (451) confessed Christ in \"two natures, without confusion, without change, without division, without separation.\" It condemned Nestorius, who split Christ into two persons — and also:",
    "options": [
      "Eutyches, who blended the two natures into one",
      "Arius, who denied the Son's deity",
      "the Docetists, who denied Christ had a real body",
      "Sabellius, who denied the three Persons"
    ],
    "correctIndex": 0,
    "explanation": "The four \"withouts\" guard both flanks at once: the natures are neither divided into two persons nor fused into a third kind of thing."
  },
  {
    "id": "d1-l2-chalcedon-defined",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      9
    ],
    "question": "The Council of Chalcedon (451) is the council that formally defined:",
    "options": [
      "how the divine and human natures relate in the one person of Christ",
      "the doctrine of the Trinity",
      "which books belong in the New Testament",
      "that Christ has both a divine and a human will"
    ],
    "correctIndex": 0,
    "explanation": "Chalcedon's subject was the person of Christ. The Trinity was settled at Nicaea/Constantinople; the two-wills question at Constantinople III (681); the canon was never fixed by a single council decree."
  },
  {
    "id": "d1-l2-yom-kippur",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      13
    ],
    "question": "On the Day of Atonement, the act the high priest performed once a year — which Hebrews says Christ fulfilled once for all — was:",
    "options": [
      "entering the Holy of Holies with sacrificial blood",
      "breaking bread with the people",
      "reading the covenant aloud to the nation",
      "lighting the seven-branched lampstand"
    ],
    "correctIndex": 0,
    "explanation": "Hebrews 9:12: Christ \"entered the holy place once for all... by His own blood,\" the true and final Day of Atonement."
  },
  {
    "id": "d1-l2-firstfruits",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      14
    ],
    "question": "Paul calls the risen Christ \"the firstfruits of those who are asleep\" (1 Cor 15:20) to make the point that:",
    "options": [
      "His resurrection is the beginning and guarantee of ours",
      "He was the first person ever restored to life",
      "only the apostles will share in resurrection",
      "resurrection is a picture, not a bodily event"
    ],
    "correctIndex": 0,
    "explanation": "Firstfruits are the first of a harvest that is sure to follow. Christ raised is the pledge that His people will be raised too."
  },
  {
    "id": "d1-l2-right-hand",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      15
    ],
    "question": "The Nicene Creed confesses that Christ \"ascended into heaven and is seated at the right hand of the Father.\" Being \"seated at the right hand\" signifies:",
    "options": [
      "active rule and authority over all things",
      "rest from His work, with rule handed back to the Father",
      "a fixed location He waits in until He returns",
      "an equality with the Father that He had given up on earth"
    ],
    "correctIndex": 0,
    "explanation": "The right hand is the place of power. The ascension is Christ's enthronement — our own human nature, in His person, now reigns (Eph 4:10)."
  },
  {
    "id": "d1-l2-virgin-birth-creeds",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      10
    ],
    "question": "The virgin birth, confessed in both the Apostles' and Nicene Creeds, safeguards two truths about Jesus at once: His true humanity (born of Mary) and:",
    "options": [
      "His divine origin — conceived by the Spirit, not by human will",
      "His sinlessness, which could be secured no other way",
      "His legal descent from David, traced through Joseph",
      "His existence before the world was made"
    ],
    "correctIndex": 0,
    "explanation": "Born of Mary, He is genuinely one of us; conceived by the Spirit, His coming is God's own act, not a human achievement. (Scripture never makes the virgin birth the mechanism of His sinlessness.)"
  },
  {
    "id": "d1-l2-nicodemus",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      17
    ],
    "question": "Jesus told Nicodemus that no one can see the kingdom of God without:",
    "options": [
      "being born again, from above, by the Spirit",
      "being circumcised as a son of Abraham",
      "keeping the law of Moses without fault",
      "being baptized by John in the Jordan"
    ],
    "correctIndex": 0,
    "explanation": "John 3. Entrance into the kingdom is not reform or pedigree but a new birth that only the Spirit can give."
  },
  {
    "id": "d1-l2-glory-to-glory",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      18
    ],
    "question": "\"We all, with unveiled face, beholding the glory of the Lord, are being transformed... from glory to glory\" (2 Corinthians 3:18) is the anchor verse for:",
    "options": [
      "sanctification",
      "regeneration",
      "justification",
      "glorification"
    ],
    "correctIndex": 0,
    "explanation": "Regeneration is the new birth, justification the verdict, glorification the future state. This verse — transformation \"from glory to glory\" — is the present, ongoing work: sanctification."
  },
  {
    "id": "d1-l2-imputed-righteousness",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      27
    ],
    "question": "The Reformers taught that in justification God credits the believer with:",
    "options": [
      "the righteousness of Christ, reckoned to their account",
      "a righteousness of their own that faith gradually produces",
      "the surplus merits of the saints",
      "a clean slate — the past wiped, with nothing put in its place"
    ],
    "correctIndex": 0,
    "explanation": "\"God credits Christ's perfect obedience to our account.\" We are counted righteous not because we have become so, but because Christ's record is reckoned as ours."
  },
  {
    "id": "d1-l2-augustine-pelagius",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      22
    ],
    "question": "Augustine developed and defended the doctrine of original sin against:",
    "options": [
      "Pelagius",
      "Arius",
      "Nestorius",
      "Marcion"
    ],
    "correctIndex": 0,
    "explanation": "Pelagius taught that people can choose good without grace. Augustine held that Adam's fall left all humanity needing grace even to will the good."
  },
  {
    "id": "d1-l2-romans4-justification",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      27
    ],
    "question": "\"To the one who does not work but believes in Him who justifies the ungodly, his faith is credited as righteousness\" (Romans 4:5) is the anchor verse for:",
    "options": [
      "justification",
      "faith",
      "grace",
      "repentance"
    ],
    "correctIndex": 0,
    "explanation": "Paul's sharpest statement that righteousness is credited, not earned — the verse Luther built the Reformation recovery of justification on."
  },
  {
    "id": "d1-l2-gospel-first-importance",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      23
    ],
    "question": "Paul says the message he \"received\" and \"passed on... as of first importance\" (1 Corinthians 15:3–4) is that:",
    "options": [
      "Christ died for our sins, was buried, and was raised on the third day",
      "we are to love God with all our heart and our neighbor as ourselves",
      "the kingdom of God has come near",
      "the Spirit is poured out on all who ask"
    ],
    "correctIndex": 0,
    "explanation": "Each other option is a true part of Jesus' message, but Paul names the death-burial-resurrection as the core content of the gospel itself."
  },
  {
    "id": "d1-l2-faith-empty-hand",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      24
    ],
    "question": "\"By grace you have been saved through faith... not as a result of works, so that no one may boast\" (Ephesians 2:8–9). In this verse, faith is:",
    "options": [
      "the empty hand that receives the gift",
      "the work that earns the reward",
      "a level of certainty God requires",
      "the merit God accepts in place of obedience"
    ],
    "correctIndex": 0,
    "explanation": "Faith saves not because it is a great achievement but because of what it lays hold of. The moment faith becomes something we're credited for, grace stops being grace."
  },
  {
    "id": "d1-l2-luther-reformation",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      27
    ],
    "question": "Which discovery of Martin Luther's touched off the Protestant Reformation?",
    "options": [
      "that we are made right with God through faith in Christ, not by our own works",
      "that church services should be held in the local language, not Latin",
      "that the Bible should be printed cheaply for ordinary people to read",
      "that priests should be free to marry"
    ],
    "correctIndex": 0,
    "explanation": "The other three were real changes the Reformation brought, but they followed from the discovery at its center: reading Romans, Luther saw that God's righteousness is a gift received by faith, not a standard he had to reach."
  },
  {
    "id": "d1-l2-justification-meaning",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      27
    ],
    "question": "Which statement best states what justification means?",
    "options": [
      "God legally declares the sinner righteous in Christ",
      "God gradually makes the sinner holy over a lifetime",
      "God overlooks the sin for Christ's sake",
      "God rewards persevering faith with righteousness"
    ],
    "correctIndex": 0,
    "explanation": "Option 2 is sanctification. Option 3 misses that Christ's righteousness is actually credited to us. Option 4 turns faith into a merit. Justification is a verdict, declared once and complete."
  },
  {
    "id": "d1-l2-abba-adoption",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      29
    ],
    "question": "\"You have received a spirit of adoption as sons, by which we cry out, 'Abba! Father!'\" (Romans 8:15) anchors the doctrine of:",
    "options": [
      "adoption",
      "regeneration",
      "justification",
      "assurance"
    ],
    "correctIndex": 0,
    "explanation": "Regeneration is the new birth, justification the verdict, assurance the confidence that follows. This verse names the new family standing — adoption."
  },
  {
    "id": "d1-l2-calvin-hinge",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      28
    ],
    "question": "John Calvin called union with Christ \"the hinge of salvation,\" meaning that:",
    "options": [
      "apart from being joined to Christ, everything He accomplished stays useless to us",
      "it is the one doctrine on which the Reformers could not agree",
      "it replaces the need for personal faith",
      "it is a further blessing added some time after justification"
    ],
    "correctIndex": 0,
    "explanation": "Calvin's point: the cross and resurrection only become ours because the Spirit unites us to the One who died and rose."
  },
  {
    "id": "d1-l2-jeremiah-new-covenant",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      30
    ],
    "question": "The new covenant that Jesus sealed in His blood was promised centuries earlier by:",
    "options": [
      "Jeremiah (31:31–34), quoted in full in Hebrews 8",
      "Moses, at the second giving of the law",
      "David, in the royal psalms",
      "Malachi, in the last book of the Old Testament"
    ],
    "correctIndex": 0,
    "explanation": "Jeremiah's promise — the law written on the heart, sins remembered no more — is the longest Old Testament quotation anywhere in the New."
  },
  {
    "id": "d1-l2-theopneustos-verse",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      33
    ],
    "question": "The Greek word theopneustos (\"God-breathed\") appears in:",
    "options": [
      "2 Timothy 3:16",
      "John 1:1",
      "2 Peter 1:21",
      "Hebrews 4:12"
    ],
    "correctIndex": 0,
    "explanation": "Each reference is a real text about God's word or the Word — but \"All Scripture is theopneustos\" is Paul to Timothy. (2 Peter 1:21 is close in theme: \"men moved by the Holy Spirit spoke from God.\")"
  },
  {
    "id": "d1-l2-sola-scriptura",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      34
    ],
    "question": "The Reformation principle sola scriptura means that:",
    "options": [
      "Scripture is the final authority, above tradition and church decree",
      "Scripture is the only book a Christian may read",
      "the Bible interprets itself with no need of teachers",
      "only the recorded words of Jesus carry authority"
    ],
    "correctIndex": 0,
    "explanation": "Sola scriptura doesn't deny the value of tradition, teachers, or creeds — it puts them all under the higher authority of God's written word."
  },
  {
    "id": "d1-l2-baptism-romans6",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      38
    ],
    "question": "Paul explains the meaning of baptism in Romans 6 as:",
    "options": [
      "being buried and raised with Christ",
      "a washing that removes the guilt of daily sins",
      "a pledge to keep the moral law",
      "a rite that completes what faith leaves unfinished"
    ],
    "correctIndex": 0,
    "explanation": "\"Buried with Him through baptism into death... so we too might walk in newness of life.\" The going-under and coming-up enact dying and rising with Christ."
  },
  {
    "id": "d1-l2-koinonia-sharing",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      39
    ],
    "question": "Paul's word for what happens at the Lord's table, koinōnia, means the meal is:",
    "options": [
      "a real sharing in the body and blood of Christ",
      "only a mental exercise of remembering a past event",
      "a fresh sacrifice of Christ offered each time",
      "a private moment between the believer and God alone"
    ],
    "correctIndex": 0,
    "explanation": "\"The cup... is it not a koinōnia in the blood of Christ?\" More than a memorial, less than a re-sacrifice — genuine participation in Christ, and in one another as one body."
  },
  {
    "id": "d1-l2-body-organism",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      37
    ],
    "question": "When Paul calls the church \"the body of Christ,\" his point is that believers are:",
    "options": [
      "one living body, mutually dependent, with Christ as the head",
      "a well-run organization with Christ as its founder",
      "separate branches that do not need one another",
      "a building in which Christ is only the cornerstone"
    ],
    "correctIndex": 0,
    "explanation": "The metaphor is an organism, not an institution — animated by Christ, so that \"if one member suffers, all suffer together\" (1 Cor 12)."
  },
  {
    "id": "d1-l2-martyria",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      45
    ],
    "question": "The Greek word martyria (\"witness\") came, over time, also to mean \"martyrdom\" because:",
    "options": [
      "many early Christians sealed their testimony with their death",
      "witnessing could only be done in a court of law",
      "the word originally meant \"to suffer\"",
      "only those who had been martyred were permitted to evangelize"
    ],
    "correctIndex": 0,
    "explanation": "To witness to Christ under Rome could cost your life. The word for \"testimony\" absorbed the price often paid to give it."
  },
  {
    "id": "d1-l2-mathetes-rabbi",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      40
    ],
    "question": "In the first century, being someone's mathētēs (\"disciple\") meant:",
    "options": [
      "following a teacher everywhere, learning by watching and imitating",
      "enrolling in a school for a course of study",
      "making a one-time profession of belief",
      "supporting a teacher with money"
    ],
    "correctIndex": 0,
    "explanation": "A disciple shared the rabbi's whole life. Jesus calls for the same — not agreement at a distance but a life spent following."
  },
  {
    "id": "d1-l2-maranatha",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      46
    ],
    "question": "The earliest recorded Christian prayer, Maranatha (\"Come, Lord!\"), expressed the church's:",
    "options": [
      "longing for Christ's return",
      "gratitude for the resurrection",
      "plea for the Spirit to be poured out",
      "sorrow under persecution"
    ],
    "correctIndex": 0,
    "explanation": "1 Corinthians 16:22. From the first, the church lived leaning toward the parousia — \"Come, Lord Jesus.\""
  },
  {
    "id": "d1-l2-greek-immortality",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      47
    ],
    "question": "Confessing the bodily resurrection set early Christianity apart from Greek philosophy, which taught instead:",
    "options": [
      "the immortality of the soul, freed from the body",
      "the extinction of the person at death",
      "endless cycles of reincarnation",
      "the sleep of the soul until judgment"
    ],
    "correctIndex": 0,
    "explanation": "Greek thought treated the body as a prison to escape. Christians confess the body raised — \"all who are in the tombs will hear His voice\" (John 5:28)."
  },
  {
    "id": "d1-l2-judgment-seat-believer",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      48
    ],
    "question": "\"We must all appear before the judgment seat of Christ\" (2 Corinthians 5:10). For those who trust Christ, this judgment means:",
    "options": [
      "they are declared righteous by grace and openly vindicated",
      "their salvation is still in the balance until the verdict is read",
      "they must answer for every sin as if it had never been forgiven",
      "they are excused from appearing at all"
    ],
    "correctIndex": 0,
    "explanation": "Judgment holds no condemnation for those in Christ (Rom 8:1). It is where God's justice is seen to be done and His people are publicly cleared."
  },
  {
    "id": "d1-l2-new-earth-renewal",
    "deckId": 1,
    "level": 2,
    "cardIds": [
      49
    ],
    "question": "The biblical hope of \"a new heaven and a new earth\" is best described as:",
    "options": [
      "the renewal of creation, with God coming down to dwell with His people",
      "the destruction of the material world so souls can live in heaven",
      "a return to the garden of Eden exactly as it first was",
      "a poetic image with no bearing on the physical world"
    ],
    "correctIndex": 0,
    "explanation": "Revelation 21: the first earth \"passed away,\" but the vision is God descending to dwell here — creation liberated, not discarded."
  },
  {
    "id": "d1-l3-trinity-drawn-in",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      5
    ],
    "question": "The doctrine of the Trinity matters for salvation because:",
    "options": [
      "we are drawn into the love the Father, Son, and Spirit have always shared",
      "it is a puzzle designed to test whether our faith is sincere",
      "it shows God changed over time, from Father to Son to Spirit",
      "it proves God is finally beyond human understanding"
    ],
    "correctIndex": 0,
    "explanation": "The \"divine dance\" is not a riddle to solve. Salvation is being included, in Christ and by the Spirit, in the communion that God has always been."
  },
  {
    "id": "d1-l3-imago-dei-dignity",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      7
    ],
    "question": "That every person bears God's image is the foundation for:",
    "options": [
      "human dignity — and the call to see Christ in the least of these",
      "the belief that people are basically good by nature",
      "the idea that every religion is equally true",
      "the claim that humans are only unusually clever animals"
    ],
    "correctIndex": 0,
    "explanation": "The image is defaced by sin but never erased. It grounds why every human life has worth, regardless of usefulness, status, or condition."
  },
  {
    "id": "d1-l3-why-god-and-man",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      11
    ],
    "question": "Why must the Savior be both fully God and fully human?",
    "options": [
      "as man He can stand in our place; as God His work has infinite worth",
      "so that He could feel both joy and sorrow like us",
      "so that an old prophecy about a God-man would come true",
      "so that His teaching would carry more authority"
    ],
    "correctIndex": 0,
    "explanation": "A substitute must belong to those he represents — so, human. But no mere human could bear the weight of the world's sin and win — so, God. Both, or no gospel."
  },
  {
    "id": "d1-l3-atonement-pictures",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      13
    ],
    "question": "The New Testament describes what the cross achieved through several pictures. Which one centers on a broken relationship restored — enemies made friends, the far-off brought near?",
    "options": [
      "reconciliation",
      "ransom — a price paid to free a captive",
      "propitiation — God's wrath turned away",
      "redemption — being bought back out of slavery"
    ],
    "correctIndex": 0,
    "explanation": "All four are real biblical images of the one cross. \"God was in Christ reconciling the world to Himself\" (2 Cor 5:19) is the relational one: the enmity is ended, and we are brought home."
  },
  {
    "id": "d1-l3-resurrection-guarantees-ours",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      14
    ],
    "question": "Christ's resurrection is not only His own vindication. It is also:",
    "options": [
      "the guarantee and pattern of the believer's resurrection",
      "a private miracle with no wider consequence",
      "proof that the human soul is naturally immortal",
      "the moment He first became the Son of God"
    ],
    "correctIndex": 0,
    "explanation": "\"The firstfruits of those who are asleep\" (1 Cor 15:20). Because He was raised bodily, His people will be too — same event, same kind of life."
  },
  {
    "id": "d1-l3-ascension-humanity-reigns",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      15
    ],
    "question": "The ascension means that, right now:",
    "options": [
      "a glorified human being rules at the center of all things",
      "Christ is absent and inactive until He returns",
      "His human nature was left behind on earth",
      "the Spirit stepped in as a lesser replacement"
    ],
    "correctIndex": 0,
    "explanation": "Our own nature, in the person of the Son, is enthroned at the Father's right hand. Where the Head has gone, the body will follow."
  },
  {
    "id": "d1-l3-regeneration-begins-life",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      17
    ],
    "question": "Regeneration is the new birth by the Spirit. Its place in the Christian life is that it:",
    "options": [
      "begins it — the start of new life, not a later goal to reach",
      "completes it — nothing of importance follows",
      "is needed by some believers but not others",
      "is simply another name for sanctification"
    ],
    "correctIndex": 0,
    "explanation": "You are born again once; you grow for a lifetime. Regeneration is the door, sanctification the road."
  },
  {
    "id": "d1-l3-indwelling-body-temple",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      21
    ],
    "question": "Because the Spirit indwells every believer, the New Testament calls the body:",
    "options": [
      "a temple — God's dwelling, to be honored",
      "a prison the soul must escape",
      "irrelevant, since only the soul matters to God",
      "neutral, neither good nor bad in itself"
    ],
    "correctIndex": 0,
    "explanation": "\"You are a temple of God and the Spirit of God dwells in you\" (1 Cor 3:16). What we do with the body is not spiritually indifferent."
  },
  {
    "id": "d1-l3-fall-makes-grace-necessary",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      22
    ],
    "question": "Which doctrine describes the condition that makes grace necessary?",
    "options": [
      "sin and the fall",
      "repentance",
      "suffering",
      "discipleship"
    ],
    "correctIndex": 0,
    "explanation": "Grace is unearned rescue; it only means anything against a fallen, helpless condition. \"Where sin increased, grace abounded all the more\" (Romans 5:20)."
  },
  {
    "id": "d1-l3-sin-is-condition",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      22
    ],
    "question": "Scripture treats sin as more than wrong actions. It is also:",
    "options": [
      "a broken condition we are born into — needing rescue, not just correction",
      "a bad habit that enough willpower can break",
      "an illusion that fades once a person knows better",
      "a problem that only affects some kinds of people"
    ],
    "correctIndex": 0,
    "explanation": "\"We don't just commit sins; we are sinners who need rescue.\" This is why the answer is a new birth and a Savior, not merely better behavior."
  },
  {
    "id": "d1-l3-union-is-the-ground",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      28
    ],
    "question": "Justification, adoption, sanctification, and glorification all come to us by way of:",
    "options": [
      "union with Christ",
      "repeated acts of faith that keep them active",
      "the sacraments administered by the church",
      "a gradual growth in personal holiness"
    ],
    "correctIndex": 0,
    "explanation": "None of Christ's benefits reach us in isolation. They are ours only because the Spirit joins us to Christ Himself — everything else follows from that."
  },
  {
    "id": "d1-l3-faith-that-works",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      24,
      25
    ],
    "question": "How do faith and works relate in salvation?",
    "options": [
      "we are saved by faith alone, but faith that is alive bears the fruit of works",
      "works supply part of the merit and faith supplies the rest",
      "works come first, and faith completes what they begin",
      "works have no place in the Christian life at all"
    ],
    "correctIndex": 0,
    "explanation": "Paul: saved by grace through faith, not works. James: faith without works is dead. Not a contradiction — a living faith always shows."
  },
  {
    "id": "d1-l3-repentance-and-faith",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      25,
      26
    ],
    "question": "Repentance and faith in conversion are:",
    "options": [
      "one turning seen from two sides — from sin, and to Christ",
      "two separate stages, often years apart",
      "repentance for unbelievers, faith for believers",
      "alternatives, where either one is enough"
    ],
    "correctIndex": 0,
    "explanation": "You cannot turn to Christ without turning from what you trusted before. They are the front and back of a single step."
  },
  {
    "id": "d1-l3-kingdom-already-not-yet",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      32
    ],
    "question": "When Jesus announced \"the kingdom of God is at hand,\" the New Testament goes on to picture the kingdom as:",
    "options": [
      "already begun in Christ, and not yet complete",
      "entirely future, arriving only when He returns",
      "entirely present, fully here in its final form now",
      "only an inward feeling, never anything outward"
    ],
    "correctIndex": 0,
    "explanation": "Christ reigns now in His people; the kingdom comes in fullness at His return. The church lives in the overlap of the ages."
  },
  {
    "id": "d1-l3-new-covenant-power",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      30
    ],
    "question": "The new covenant differs from the old chiefly in that:",
    "options": [
      "the Spirit writes God's law on the heart and gives power to keep it",
      "God no longer cares how His people live",
      "it applies only to the nation of Israel",
      "it removes the need for forgiveness of sins"
    ],
    "correctIndex": 0,
    "explanation": "Jeremiah's promise: not new rules, but a new heart and an indwelling Spirit — the power the law could command but never supply."
  },
  {
    "id": "d1-l3-justification-to-adoption",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      27,
      29
    ],
    "question": "Justification declares us righteous. Which doctrine names the new relationship we are brought into?",
    "options": [
      "adoption",
      "regeneration",
      "sanctification",
      "salvation"
    ],
    "correctIndex": 0,
    "explanation": "Justification is the courtroom — the verdict \"not guilty.\" Adoption is the family room — \"my child.\" Romans 8:15: the Spirit of adoption by which we cry \"Abba, Father.\""
  },
  {
    "id": "d1-l3-justified-vs-sanctified",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      27,
      18
    ],
    "question": "A believer says, \"I was justified the day I trusted Christ, and I've been sanctified a little more every day since.\" What distinction is she making correctly?",
    "options": [
      "a finished verdict vs. an ongoing work",
      "a legal change vs. a relational one",
      "God's part vs. our part",
      "the Father's work vs. the Spirit's"
    ],
    "correctIndex": 0,
    "explanation": "Justification is once-for-all and complete; sanctification is lifelong and gradual. Both are grace. Collapsing the two produces either pride or despair."
  },
  {
    "id": "d1-l3-regeneration-vs-adoption",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      17,
      29
    ],
    "question": "Regeneration and adoption both happen at conversion, but they answer different questions. Regeneration answers \"what changed inside me?\" Adoption answers:",
    "options": [
      "\"whose family am I in?\"",
      "\"am I really forgiven?\"",
      "\"will I make it to the end?\"",
      "\"what do I have to do now?\""
    ],
    "correctIndex": 0,
    "explanation": "Regeneration = a new nature, born of the Spirit (Titus 3:5). Adoption = a new status, a permanent place in God's household."
  },
  {
    "id": "d1-l3-ot-points-to-christ",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      35
    ],
    "question": "To read the Old Testament as a Christian is to:",
    "options": [
      "look for how it prepares for and points forward to Christ",
      "treat it as no longer relevant to believers",
      "read it only for timeless moral rules",
      "assume it speaks of a different God than the New Testament"
    ],
    "correctIndex": 0,
    "explanation": "The risen Jesus, \"beginning with Moses and all the Prophets,\" showed the disciples how all Scripture spoke of Him (Luke 24:27)."
  },
  {
    "id": "d1-l3-church-local-and-universal",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      36
    ],
    "question": "The New Testament speaks of the church as both:",
    "options": [
      "every believer everywhere, and the particular congregation you gather with",
      "a building, and the organization that runs it",
      "the clergy, and separately the laity",
      "Israel, and separately the nations"
    ],
    "correctIndex": 0,
    "explanation": "One church, seen two ways: the universal body of all the redeemed, and the local assembly where that body takes visible shape."
  },
  {
    "id": "d1-l3-sacraments-visible-signs",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      38,
      39
    ],
    "question": "Baptism and the Lord's Supper are set apart from other practices because they:",
    "options": [
      "are visible signs Christ Himself gave of an invisible grace",
      "earn grace for the person who performs them correctly",
      "are symbols with no real link to what they point to",
      "take the place of personal faith in Christ"
    ],
    "correctIndex": 0,
    "explanation": "Water, bread, and cup are given by Christ to show and seal what the gospel promises — dying and rising with Him, sharing in His body and blood."
  },
  {
    "id": "d1-l3-suffering-forms-christ",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      44
    ],
    "question": "The New Testament does not promise escape from suffering. Instead it says God uses trials to:",
    "options": [
      "refine faith and form the character of Christ in us",
      "punish believers for sins they have hidden",
      "earn extra reward for those strong enough to bear it",
      "expose which people were never really Christians"
    ],
    "correctIndex": 0,
    "explanation": "\"The testing of your faith produces endurance\" (Jas 1:3). We are not promised a way around suffering but God's presence within it, working good."
  },
  {
    "id": "d1-l3-perseverance-preserved",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      43
    ],
    "question": "Perseverance does not mean a believer never struggles or doubts. It means:",
    "options": [
      "God is faithful to finish His work, and calls His people to endure to the end",
      "a Christian may live any way at all and remain secure",
      "salvation must be re-earned through each new day",
      "any season of doubt proves that salvation was never real"
    ],
    "correctIndex": 0,
    "explanation": "Two things held together: \"He who began a good work in you will complete it\" (Phil 1:6), and \"you have need of endurance\" (Heb 10:36). Faith may grow weak, but it is meant to press on, kept by God."
  },
  {
    "id": "d1-l3-blessed-hope-motivates",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      46
    ],
    "question": "The \"blessed hope\" of Christ's return is meant to produce:",
    "options": [
      "watchful, holy living and faithful service now",
      "date-setting and withdrawal from ordinary life",
      "mainly fear of being caught unprepared",
      "indifference, since no one knows the timing"
    ],
    "correctIndex": 0,
    "explanation": "Because He is coming, and could come at any time, the New Testament says: stay awake, keep working, live clean."
  },
  {
    "id": "d1-l3-body-and-earth-together",
    "deckId": 1,
    "level": 3,
    "cardIds": [
      47,
      49
    ],
    "question": "The resurrection of the body and the new earth belong together because:",
    "options": [
      "God redeems the whole creation — embodied people for a renewed world",
      "both are only word-pictures for a non-physical heaven",
      "the body is raised, but the earth is finally destroyed",
      "the earth is renewed, but people remain disembodied spirits"
    ],
    "correctIndex": 0,
    "explanation": "The Christian hope is not rescue from the material world but its renewal — raised people at home on a healed earth, with God dwelling among them."
  }
];
